/* Chronoscope — Atlas expansion (Build 2). New holes and ideas.
   Exploratory entries (tag HYPOTHESIS, who "Will & Claude") are our own thinking, not mainstream physics. */
Chrono.HOLES.push(
  { id: "H8", name: "Is energy conserved cosmically?", tag: "ESTABLISHED",
    plain: "Energy is conserved because the laws are the same at every moment (Noether's theorem). But the expanding universe changes over time, so there is no general law that its total energy is conserved. Light crossing the cosmos loses energy to redshift; dark energy's total grows as space grows.",
    why: "Energy conservation is usually treated as sacred. At the scale of the whole universe, general relativity doesn't guarantee it — physicists disagree about how to describe this, not about the maths." },
  { id: "H9", name: "What is empty space made of?", tag: "ESTABLISHED",
    plain: "The vacuum isn't empty: quantum fields fill it, and it pushes (the Casimir effect). Quantum theory's estimate of the vacuum's energy is wrong by a factor of about 10^120 compared with the dark energy we measure — perhaps the worst prediction in physics.",
    why: "Whatever space is 'made of' — fields, a condensate, entanglement — it is the stage for time too. Dark energy (~68% of the universe) sits here." },
  { id: "H10", name: "How fast is it expanding?", tag: "ESTABLISHED",
    plain: "Two good methods measure the expansion rate and disagree: about 67 versus 73 km/s per megaparsec. Years of checking haven't closed the gap (the 'Hubble tension').",
    why: "If it isn't a measurement error, something is missing from our model of the cosmos — possibly in how time and expansion are described." },
  { id: "H11", name: "What is a dimension?", tag: "HYPOTHESIS",
    plain: "Will's challenge: physics uses dimensions constantly but has no agreed account of what makes one kind of dimension different from another. Time is usually described with questions written for space.",
    why: "Exploratory framing by Will & Claude. Mathematics defines dimension rigorously (degrees of freedom, fractional and scale-dependent dimension); the open part is a physical taxonomy of dimension types. See the Dimension Map." }
);

const E = (id, year, name, who, camp, holes, tag, outcome, plain, why, c, note, extra) =>
  Object.assign({ id, year, name, who, camp, holes, tag, outcome, plain, why, c, note }, extra || {});
const U = { rel: "unk", pred: "unk", matter: "unk", arrow: "unk", test: "unk" };
const NA = { rel: "na", pred: "na", matter: "na", arrow: "na", test: "na" };

Chrono.IDEAS.push(
  E("hinton", 1880, "The fourth dimension as a spiritual realm", "C. H. Hinton; J. Zöllner (1878)", "lens", ["H5", "H11"], "ANALOGY", "History",
    "Victorian thinkers read Flatland logic spiritually: a being in a fourth dimension could see inside closed things and appear or vanish. Hinton, who coined 'tesseract', tried to train the mind to picture 4D.",
    "Zöllner, a respected astrophysicist, claimed mediums tied knots in sealed string through the fourth dimension. The mediums were exposed; the idea was never really tested. It shaped art (Cubism, Duchamp).", NA,
    "Lens: shows the pattern people have long seen between higher dimensions and 'higher realms' — and why it needs a testable signature."),
  E("mm", 1887, "No aether wind", "Michelson & Morley", "bench", ["H9"], "ESTABLISHED", "Repeated with modern lasers",
    "Light's speed is the same in every direction, whatever Earth's motion — no 'wind' from a medium we move through.",
    "Modern laser versions are about a trillion times more precise and still find no wind. What's ruled out is a medium with a rest frame — not every kind of underlying structure.", NA,
    "A constraint any 'membrane' idea must pass: it can't have a wind."),
  E("noether", 1918, "Symmetry makes conservation", "Emmy Noether", "found", ["H8"], "ESTABLISHED", "Mainstream",
    "Every conservation law comes from a symmetry. Energy is conserved because the laws are the same at every moment; momentum because they're the same everywhere.",
    "It turns conservation from a rule into a consequence — and tells you exactly when it can fail: when time itself isn't uniform, as in an expanding universe.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "no", test: "yes" }, "Energy is time's conserved partner."),
  E("tired", 1929, "Tired light", "Fritz Zwicky", "cosmos", ["H10"], "SPECULATIVE", "Tested and ruled out",
    "Maybe distant galaxies look redder because light loses energy on its long journey, not because space expands.",
    "A natural idea, taken seriously for decades. It fails several tests: distant supernovae unfold in slow motion by exactly the redshift factor (DES, 2024); the microwave background keeps a perfect thermal spectrum and was hotter in the past by the same factor; distant galaxies aren't blurred.",
    { rel: "part", pred: "yes", matter: "yes", arrow: "na", test: "no" }, "A model of how a good idea is tested — see 'How sure are we?'"),
  E("foam", 1955, "Spacetime foam", "John Wheeler", "less", ["H9", "H1"], "SPECULATIVE", "Open",
    "Smooth at everyday scales, spacetime may churn and fluctuate at the tiniest scales (~10⁻³⁵ m).",
    "If quantum rules apply to geometry itself, geometry should fluctuate. Calm from afar, turbulent up close.",
    { rel: "yes", pred: "part", matter: "yes", arrow: "na", test: "part" }, "Searches for foam effects in light from distant bursts have found none yet."),
  E("tryon", 1973, "The zero-energy universe", "Edward Tryon", "cosmos", ["H6", "H8"], "SPECULATIVE", "Debated",
    "The positive energy of matter may be exactly cancelled by the negative energy of gravity, so the universe's total energy could be zero.",
    "Then 'something from nothing' costs nothing: the universe could arise as a fluctuation.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "na", test: "no" }, "Depends on how gravitational energy is defined — itself contested (H8)."),
  E("prigogine", 1977, "Order from energy flow", "Ilya Prigogine (Nobel 1977)", "origin", ["H3"], "ESTABLISHED", "Mainstream",
    "Energy flowing through a system can create structure spontaneously — convection cells, chemical clocks, arguably life. 'Dissipative structures'.",
    "Entropy's increase isn't only decay: the flow from order to disorder is where complexity is built.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "yes", test: "yes" }, "Earth sends back ~20 infrared photons for each visible one it receives — life lives in that gap."),
  E("unruh", 1981, "Black holes in a fluid", "Bill Unruh; Steinhauer (2016–19)", "found", ["H7"], "ESTABLISHED", "Lab analogues built",
    "Sound in a flowing fluid behaves like light near a black hole: where the flow outruns sound, sound can't escape.",
    "Labs have made such 'sonic black holes' in ultracold atoms and seen analogue Hawking radiation.",
    { rel: "na", pred: "yes", matter: "na", arrow: "na", test: "yes" }, "Analogues show the maths; they don't prove real black holes behave identically."),
  E("jacobson", 1995, "Gravity as thermodynamics", "Ted Jacobson", "less", ["H9", "H1"], "CONTESTED", "Influential",
    "Einstein's equations can be derived as an equation of state — like fluid laws emerging from molecules.",
    "A strong hint that spacetime is made of something: gravity might be the thermodynamics of hidden microscopic parts.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "part", test: "unk" }),
  E("add", 1998, "Large extra dimensions", "Arkani-Hamed, Dimopoulos, Dvali", "more", ["H5"], "SPECULATIVE", "Squeezed by tests",
    "Gravity is weak because it spreads into extra space dimensions (up to ~a millimetre) where other forces can't go.",
    "It made testable predictions: gravity's law should change at small distances; the LHC might make micro black holes.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "na", test: "yes" }, "Gravity's inverse-square law holds down to tens of micrometres; no micro black holes seen."),
  E("rs", 1999, "A warped fifth dimension", "Randall & Sundrum", "more", ["H5", "H9"], "SPECULATIVE", "Open",
    "Our universe is a 3D 'sheet' (brane) in a curved higher-dimensional space. Light and matter are stuck on the sheet; gravity is not.",
    "The warping explains why gravity is so much weaker than other forces.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "na", test: "part" }),
  E("dgp", 2000, "Acceleration without dark energy", "Dvali, Gabadadze, Porrati", "cosmos", ["H9", "H10"], "SPECULATIVE", "Self-accelerating version ruled out",
    "Gravity leaks off our brane into a fifth dimension at huge distances, so expansion speeds up by itself — no dark energy needed.",
    "Exactly the Flatland intuition: an unseen dimension showing up as an unexplained effect.",
    { rel: "yes", pred: "part", matter: "yes", arrow: "na", test: "no" }, "Killed by an instability and a poorer fit to data — but it's the template for the idea."),
  E("ekpyrotic", 2001, "The cyclic, colliding-brane universe", "Khoury, Ovrut, Steinhardt, Turok", "origin", ["H6", "H3"], "SPECULATIVE", "Open",
    "The Big Bang was a collision of two 3D branes in a fifth dimension — and it repeats in cycles.",
    "Replaces a beginning with a bounce; offers an alternative to inflation.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "part", test: "part" }),
  E("volovik", 2003, "The universe in a helium droplet", "Grigory Volovik", "less", ["H9"], "SPECULATIVE", "Open",
    "The vacuum behaves like a quantum fluid; particles and even spacetime-like behaviour emerge from it, as in superfluid helium.",
    "A modern 'medium' with no wind — compatible with relativity at everyday scales.",
    { rel: "part", pred: "yes", matter: "yes", arrow: "na", test: "unk" }),
  E("cdt", 2005, "Dimension shrinks at small scales", "Ambjørn, Jurkiewicz, Loll", "less", ["H5", "H11"], "SPECULATIVE", "Several approaches agree",
    "Simulations of quantum spacetime find it behaves 4-dimensional at large scales but about 2-dimensional at the tiniest.",
    "Dimension may not be a fixed building block but something that depends on how closely you look.",
    { rel: "yes", pred: "yes", matter: "unk", arrow: "na", test: "unk" }),
  E("timescape", 2007, "Timescape: clocks in voids", "David Wiltshire (supernova analysis 2024–25)", "cosmos", ["H10", "H9", "H1"], "CONTESTED", "Debated",
    "Clocks tick at different rates in empty voids and dense regions. Averaging correctly may make cosmic acceleration — and so dark energy — an illusion.",
    "A proposal where time itself explains the dark sector, using only ordinary general relativity.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "na", test: "part" }, "Most cosmologists remain sceptical; the fits are disputed."),
  E("river", 2008, "The river model of black holes", "Hamilton & Lisle", "found", ["H7"], "ESTABLISHED", "Mainstream view of GR",
    "Space flows into a black hole like a river, reaching light speed at the horizon. Light swimming out can't beat the current inside.",
    "An exact way of picturing ordinary general relativity — see the River lab.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "na", test: "yes" }),
  E("cpt", 2018, "A mirror universe before the Big Bang", "Boyle, Finn, Turok", "origin", ["H6", "H3"], "SPECULATIVE", "Open",
    "Our universe is paired with a mirror anti-universe on the other side of the Big Bang; together they form a balanced whole.",
    "It explains some features of the early universe and makes a dark-matter prediction.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "yes", test: "part" }),
  E("hubble", 2019, "The Hubble tension", "SH0ES (Riess) vs Planck", "cosmos", ["H10"], "ESTABLISHED", "Unresolved",
    "Local measurements give ~73 km/s/Mpc; the early-universe method gives ~67. The disagreement has grown more significant with better data.",
    "Either a hidden error or missing physics.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "na", test: "yes" }),
  E("desi", 2024, "Is dark energy weakening?", "DESI collaboration (2024–25)", "cosmos", ["H9", "H10"], "CONTESTED", "Hints, not proof",
    "The largest 3D map of the universe hints that dark energy may be changing over time, not constant.",
    "If confirmed, the future of expansion — even a slowdown or reversal — reopens.",
    { rel: "yes", pred: "yes", matter: "yes", arrow: "na", test: "yes" }),

  /* ---- Exploratory: Will & Claude (not mainstream physics) ---- */
  E("wc-membrane", 2026, "The membrane: one ocean", "Will & Claude", "less", ["H9", "H1"], "HYPOTHESIS", "Exploratory",
    "Light, gravity and matter aren't separate things in space — they are all features of one underlying medium, the way waves and currents are all just the ocean. Matter arises from the membrane, not the other way round.",
    "Partly mainstream already: in quantum field theory particles are ripples of fields. The exploratory step is that spacetime and fields are one medium, and that the dark sector is a property of it.",
    U, "Must pass Michelson–Morley: the medium can have no 'wind'.",
    { predicts: "Light and gravity share deep properties (both travel at c — consistent so far); the dark sector behaves like properties of the medium, not new particles.", kill: "Direct detection of dark-matter particles with no medium-like behaviour; evidence that spacetime is fundamental at every scale." }),
  E("wc-river", 2026, "Time as a turbulent river", "Will & Claude", "more", ["H1", "H3"], "HYPOTHESIS", "Exploratory",
    "Time looks like a smooth, laminar flow from afar, but up close it has rapids and whirlpools — a texture, perhaps with entropy at work inside time itself.",
    "Echoes of real ideas: spacetime foam, Oppenheim's random wobble, the river model. The exploratory step: texture as a genuine property of time.",
    U, null,
    { predicts: "Tiny excess 'noise' in the best clocks that grows in particular environments (near mass, in voids).", kill: "Optical-clock networks finding no noise beyond known sources down to the Planck-scale expectation." }),
  E("wc-timegroup", 2026, "Time as a dimension group", "Will & Claude", "more", ["H5", "H11"], "HYPOTHESIS", "Exploratory",
    "Treat time as its own group, like space, with its own native sub-dimensions: direction, texture — and properties space doesn't have: persistence, accumulation, loss of possibility.",
    "Stops describing time with questions written for space. See the Dimension Map.",
    U, null,
    { predicts: "Missing time-native properties will line up with open holes (the arrow, the 'now').", kill: "Showing every property of time reduces to geometry plus initial conditions." }),
  E("wc-layers", 2026, "Interwoven universes", "Will & Claude", "more", ["H6", "H11"], "HYPOTHESIS", "Exploratory",
    "Other 'universes' may not be elsewhere but interwoven with ours — other groupings of dimensions we don't occupy, as Flatland is interwoven with Spaceland. Long human intuitions of 'higher realms' could be read this way.",
    "Brane-world physics makes a version of this concrete. The exploratory step extends it beyond gravity.",
    U, "The hard part: a layer that doesn't interact through gravity leaves no signature physics can detect.",
    { predicts: "If gravity leaks between layers: hidden mass (dark matter?) and deviations in gravity's force law.", kill: "Gravity's law holding perfectly at all testable scales, and dark matter identified as ordinary particles." })
);
