/* Chronoscope — how each idea could be tested, and why it scores as it does on the Test bench.
   predicts : what the idea says we should see       kill : what would overturn it (for ruled-out ideas: what did)
   r        : reason for every score that isn't a plain ✓ or n/a (✓ and n/a use the generic lines in BENCH_WHY)
   First-pass judgements by Claude, made to be argued with — the Test bench lets visitors score differently.
   Keep entries short: one sentence each. Sources: sources.md. */
(function () {
  Chrono.BENCH_WHY = {
    yes: { rel: "Consistent with every test of relativity so far.", pred: "The present determines the future in the ordinary way.", matter: "Leaves atoms and particles stable.", arrow: "Offers an explanation of why time has a direction.", test: "Makes predictions that can be, or have been, checked." },
    na: "Doesn't apply — the idea makes no claim here."
  };

  const T = {
    minkowski: { predicts: "Moving clocks run slow by exactly the factor γ, and nothing with mass reaches light speed.",
      kill: "A reproducible failure of relativity's symmetry — for example light's speed depending on direction or on the motion of its source.",
      r: { arrow: "Treats past and future symmetrically; the direction of time isn't in the geometry." } },
    kk: { predicts: "Heavy copies of known particles, at energies set by the size of the curled-up dimension.",
      kill: "Colliders reaching those energies and finding no copies — though the dimension can always be assumed smaller, which is the idea's weak spot.",
      r: { matter: "Depends on fixing the size of the extra dimension, which the original theory leaves free.", test: "Its signature particles sit at energies set by an unknown size — so far out of reach." } },
    dunne: { predicts: "Dreams contain images of future events more often than chance would allow.",
      kill: "Controlled dream-record studies finding no excess over chance — which is what later attempts found.",
      r: { rel: "Never written as equations, so it can't be checked against relativity.", pred: "Without equations there's no way to say.", test: "Its one testable claim — precognitive dreams — failed when others tried to replicate it." } },
    lemaitre: { predicts: "A cooling afterglow of the hot early universe (the microwave background) and the amounts of light elements made in the first minutes.",
      kill: "No afterglow, or distant galaxies not receding. Both were found as predicted.",
      r: { arrow: "Gives time a starting point, but not the reason the start was so ordered (hole H3)." } },
    wf: { predicts: "Radiation behaves exactly as ordinary electromagnetism says — provided the far-future universe absorbs everything sent into it.",
      kill: "Evidence that the far-future universe is transparent to radiation, which would break the mechanism.",
      r: { pred: "Needs a condition on the far future (a perfect absorber), so prediction becomes global rather than step by step.", arrow: "Moves the arrow of radiation into cosmic boundary conditions — which are themselves assumed.", test: "Built to agree with ordinary electromagnetism, so it offers no distinct confirmed prediction." } },
    godel: { predicts: "A universe rotating as a whole.",
      kill: "No measurable cosmic rotation — which is what we see. As a model of our universe it fails; as an argument about time it stands.",
      r: { pred: "Contains loops in time, so the present can't freely set up the future — consistency conditions take over." } },
    wdw: { predicts: "Any quantum description of the whole universe faces a timeless equation of this kind — a framework rather than a forecast.",
      kill: "A working quantum theory of gravity in which a fundamental, external time survives.",
      r: { pred: "With no time variable, 'predicting the future' first needs a clock picked out inside the universe.", arrow: "No time, so no direction of time.", test: "No experiment yet reaches the scales where it would matter." } },
    dorling: { predicts: "In any world with two or more time dimensions, particles could decay into heavier ones.",
      kill: "A consistent multi-time theory in which an extra law restores stability — which is exactly what such theories must supply." },
    pathria: { predicts: "A universe whose size and mass sit close to the black-hole relation — which ours roughly does.",
      kill: "Critics point out the match follows automatically for any flat universe at the critical density, so it may be no clue at all.",
      r: { arrow: "Doesn't address the arrow; it depends on what the interior model says.", test: "Mostly a numerical coincidence; testable only through specific versions (see 'We live inside a black hole')." } },
    hh: { predicts: "The universe began in the simplest, smoothest possible state, with no first moment.",
      kill: "Calculations showing the proposal favours a wildly irregular start — a claim made in 2017 and still disputed.",
      r: { arrow: "Gives a smooth, simple start, which helps — but whether it truly favours our kind of start is debated.", test: "Makes statistical predictions for the early universe that are hard to separate from other models." } },
    pw: { predicts: "Clocks inside a static, entangled whole see ordinary time evolution — shown in miniature with entangled photons (2013).",
      kill: "Evidence of a fundamental external time, or the mechanism failing to extend consistently to relativity and gravity.",
      r: { rel: "The original form is non-relativistic; relativistic versions are still being worked out.", arrow: "Time emerges as correlation, but nothing picks out a direction.", test: "Lab demonstrations illustrate the mechanism; nothing yet tests it on cosmic scales." } },
    smolin: { predicts: "An upper limit on the mass of neutron stars, well under two solar masses.",
      kill: "Neutron stars of about two solar masses — found since 2010 and widely seen as a serious problem for it." },
    thermal: { predicts: "An observer's flow of time is set by the statistical state of what they observe — and it reproduces the known link between acceleration and temperature (the Unruh effect).",
      kill: "A demonstration that time's flow is independent of any statistical state. Hard to design — which is the idea's weak spot.",
      r: { arrow: "Explains why time seems to flow for coarse-grained observers, not why it flows one particular way.", test: "Reproduces known physics; no distinct new prediction yet." } },
    tegmark: { predicts: "Observers will find themselves in 3 space + 1 time dimensions.",
      kill: "A worked example of stable, predictable physics with complex structures in some other combination of dimensions." },
    bars: { predicts: "Hidden relations between apparently different one-time theories — the same system seen as different 'shadows'.",
      kill: "A consistent quantum version failing, or the predicted relations turning out false.",
      r: { test: "Offers new relations between known theories; distinct experimental predictions are few and untested." } },
    barbour: { predicts: "Arrows of time pointing away from a 'Janus point' in both directions — in cosmology, another 'after' on the far side of the Big Bang.",
      kill: "Evidence that the Big Bang was a true edge with nothing beyond, or models in which complexity fails to grow away from the minimum.",
      r: { rel: "Built on a relational rewrite of gravity; the full relativistic version (shape dynamics) is still in development.", test: "Unclear what observation would distinguish it from standard cosmology." } },
    cc: { predicts: "On the very largest scales the arrow of time is symmetric — reversed in regions far beyond our horizon.",
      kill: "Showing that an empty background can't spawn new inflating regions as the model needs — a point theorists dispute.",
      r: { test: "Most of its structure lies beyond anything we can observe." } },
    ccc: { predicts: "Circles and bright spots ('Hawking points') in the microwave background, left over from the previous aeon.",
      kill: "Independent analyses finding those features no more common than chance — which several have reported.",
      r: { arrow: "Resets the universe through geometry at each aeon, but how entropy is reset is contested." } },
    cw: { predicts: "With two times, prediction only works if the present obeys a non-local constraint.",
      kill: "A local, predictable evolution law with two times for general starting data — ruled out mathematically for this class of equations." },
    surrey: { predicts: "An open quantum system's equations, derived without picking a direction, relax toward equilibrium both ways from a chosen moment.",
      kill: "An error found in the derivation, or the symmetric form failing for realistic environments.",
      r: { arrow: "Shows the equations don't choose a direction; it doesn't explain why our universe has one.", test: "A mathematical result with no new experiment proposed." } },
    pettini: { predicts: "Entanglement correlations carrying a specific signature of the extra time dimension (the proposed 2026 test).",
      kill: "The proposed test finding nothing, or the theory failing the matter-stability and predictability hurdles.",
      r: { rel: "Must reproduce relativity in our 3+1 slice; how fully it does isn't yet shown.", pred: "The two-time predictability problem (Craig–Weinstein) isn't yet addressed.", matter: "The two-time matter instability (Dorling) isn't yet addressed.", test: "A test has been proposed but not carried out." } },
    kletetschka: { predicts: "Particle masses and other constants from the geometry of three time dimensions.",
      kill: "Showing the masses were fitted rather than derived, or any clear new prediction failing.",
      r: { rel: "Unclear how ordinary relativity is recovered.", pred: "Multi-time predictability not addressed.", matter: "Multi-time matter stability not addressed.", test: "Claims particle masses, but whether they're predictions or fits is disputed." } },
    bhu: { predicts: "Imprints of the collapse and bounce on the early universe, which its authors are working to pin down.",
      kill: "Ever more precise early-universe data matching standard cosmology with no room for bounce imprints.",
      r: { arrow: "Depends on the details of the bounce.", test: "Predictions are still being made precise; evidence claimed so far is disputed." } },
    mm: { predicts: "Light's speed is the same in every direction, whatever Earth's motion.",
      kill: "A reproducible direction-dependent light speed. Modern versions reach about one part in 10¹⁸ and see none." },
    weak: { predicts: "Specific particle decays (neutral kaons, B mesons) run at slightly different rates forwards and backwards in time.",
      kill: "Precision experiments finding perfect time symmetry in those decays — contradicting 1964, 1998 and 2012 results.",
      r: { arrow: "The violation is real but far too small, and of the wrong kind, to produce the everyday arrow of time." } },
    noether: { predicts: "Wherever the laws are the same at every moment, energy is conserved exactly.",
      kill: "Energy failing to be conserved in a system whose laws don't change over time — never seen.",
      r: { arrow: "Time symmetry gives energy conservation, not a direction." } },
    tired: { predicts: "Redshift without time dilation: distant supernovae would unfold at normal speed.",
      kill: "Supernova light curves stretched by exactly (1 + z), a perfectly thermal microwave background that was hotter in the past, and sharp distant galaxies.",
      r: { rel: "Needs light to lose energy without blurring images; no mechanism does that within known physics.", test: "It made clear predictions — and they failed." } },
    foam: { predicts: "Tiny energy-dependent delays or blurring in light that has crossed billions of light-years.",
      kill: "Searches pushing past the Planck scale and finding nothing — some versions are already constrained.",
      r: { pred: "If geometry itself fluctuates, predictions at the tiniest scales become statistical.", test: "Searched for in light from distant bursts; nothing found so far." } },
    tryon: { predicts: "A universe with zero total energy — in Tryon's version, a closed universe. Today's data show it very close to flat.",
      kill: "An agreed definition of gravitational energy under which the total is clearly not zero.",
      r: { test: "Whether the total is zero depends on how gravitational energy is defined — not something one experiment can settle." } },
    prigogine: { predicts: "Ordered patterns — convection cells, chemical oscillations — appear by themselves when energy flows through a system far from equilibrium.",
      kill: "Lasting structure forming in a closed system with no energy flow. Never seen." },
    unruh: { predicts: "Analogue horizons in fluids give off thermal noise, like Hawking radiation.",
      kill: "Well-controlled analogue experiments showing no such emission." },
    jacobson: { predicts: "Einstein's equations as an equation of state, with possible corrections under extreme conditions.",
      kill: "Gravity behaving in a way no thermodynamic system could — for example horizons whose entropy isn't set by their area.",
      r: { arrow: "Ties gravity to thermodynamics and entropy, but doesn't by itself explain the ordered start.", test: "Distinct predictions depend on what the hidden microscopic parts are." } },
    add: { predicts: "Gravity growing stronger than Newton's law at sub-millimetre distances, and micro black holes at colliders.",
      kill: "Already squeezed: the inverse-square law holds down to tens of micrometres, and the LHC made no micro black holes." },
    rs: { predicts: "Heavy 'graviton' resonances at particle colliders.",
      kill: "No resonances at any reachable energy — which pushes the model toward energies where it loses its appeal.",
      r: { test: "Its collider signature hasn't appeared, which pushes its energy scale up." } },
    dgp: { predicts: "Cosmic acceleration and a specific pattern of structure growth, with no dark energy.",
      kill: "What largely killed the self-accelerating version: a 'ghost' instability and a poorer fit to supernova and microwave-background data.",
      r: { pred: "The self-accelerating version contains an instability (a 'ghost'), undermining predictable evolution.", test: "Its distinctive expansion history fits the data worse than dark energy." } },
    ekpyrotic: { predicts: "No detectable primordial gravitational waves in the microwave background's polarisation.",
      kill: "A clear detection of primordial gravitational waves (the 'B-mode' signal).",
      r: { arrow: "Cycles don't by themselves explain the low-entropy start of each one; the model argues expansion dilutes entropy.", test: "Its key prediction is testable, and searches continue." } },
    volovik: { predicts: "Relativity is approximate: tiny violations at extreme energies, as in fluid analogues.",
      kill: "Relativity holding exactly at the highest energies ever probed.",
      r: { rel: "Relativity emerges only at low energies, as in helium; exact at every scale isn't guaranteed.", test: "Unclear what distinct observation would confirm it." } },
    cdt: { predicts: "At the tiniest scales, spacetime behaves as if it has about two dimensions.",
      kill: "The result failing in refined simulations — or, if it ever becomes possible, Planck-scale probes seeing no change.",
      r: { matter: "Matter hasn't yet been fully included in the simulations.", test: "The effect sits at scales far beyond any current experiment." } },
    timescape: { predicts: "Supernova distances that fit void-dependent clock rates better than dark energy.",
      kill: "Precision supernova and galaxy-survey data favouring dark energy decisively over timescape fits.",
      r: { test: "It makes different predictions for supernova distances; current fits are contested." } },
    river: { predicts: "Exactly what general relativity predicts — it's a rewrite of the standard black-hole solution.",
      kill: "Anything that overturns general relativity's black holes. So far black-hole images and gravitational waves agree." },
    cpt: { predicts: "Dark matter made of one specific heavy neutrino, and a lightest ordinary neutrino with zero mass.",
      kill: "A nonzero mass for all three ordinary neutrinos, or a detection of primordial gravitational waves.",
      r: { test: "Its predictions are specific but not yet tested." } },
    hubble: { predicts: "A measurement, not a theory: if the tension is real, new physics changes the expansion rate between early and late times.",
      kill: "A systematic error found that brings the two methods into agreement." },
    desi: { predicts: "Dark energy's strength changes over cosmic time.",
      kill: "Later data (DESI, Euclid, the Rubin Observatory) showing constant dark energy within tight errors." }
  };

  Chrono.IDEAS.forEach(i => { const t = T[i.id]; if (!t) return; if (!i.predicts) i.predicts = t.predicts; if (!i.kill) i.kill = t.kill; i.r = t.r || {}; });
  Chrono.benchWhy = (i, k) => { const v = i.c[k]; return (i.r && i.r[k]) || (v === "yes" ? Chrono.BENCH_WHY.yes[k] : v === "na" ? Chrono.BENCH_WHY.na : ""); };
})();
