/* Chronoscope — tour stops (D-043, UX spec Phase 1), from the signed-off `stop-plans.md` (draft 4).
   A lab is a piece of physics, written once. A stop is the question a tour asks of that lab.
   Fields: href · where (lab name) · q (the stop's question) · see (Home teaser, no spoilers) · say (tour-bar
   instruction) · look (where the evidence appears) · takeaway + tags · limit · handoff (why the next stop is
   needed) · go (optional "go deeper" links) · setup (the lab's starting state; applied by the lab's applySetup) ·
   predict: undefined = use the lab's own question · null = no guess at this stop · { q, options, answer, explain } = the stop's own.
   Guesses are saved per stop (lab:tour:stop), so a Tour 1 guess never answers a Tour 3 question. */
(function () {
  Chrono.STOPS = {
    puzzle: { name: "The puzzle of time", blurb: "If you want the big question: why is there one time, and only one? From 'do clocks agree?' to 'is it a law of nature?'", stops: [
      { href: "#clocks", where: "Clock Lab", q: "Do two perfect clocks agree?", see: "Two perfect clocks — and a surprise when one of them moves.",
        say: "Two perfect clocks, one moving at 0.87 of light speed. Count the ticks on both.", look: "the two tick counters",
        takeaway: "At 0.87 c, in your frame, the moving clock ticks about once for every two of yours. Every kind of clock follows the same rule.", tags: ["ESTABLISHED"],
        limit: "One space dimension; an ideal light clock; no gravity yet.", handoff: "Speed changes clock rates. Does gravity do the same?",
        setup: { mode: "light", v: 0.87 } },
      { href: "#river", where: "The River", q: "Does gravity change time too?", see: "A black hole drawn as space flowing inward. Can light swim out?",
        say: "Fire light outward from far away, just outside, and just inside the horizon.", look: "which flashes get out",
        takeaway: "Gravity slows clocks too. At the horizon, outward light stands still; inside, it's swept in.", tags: ["ESTABLISHED"],
        limit: "'Flowing space' is one exact way of drawing a non-rotating black hole, not the only one.", handoff: "Clocks disagree about how fast time runs. Do observers even agree on what happens at the same time?",
        predict: null },
      { href: "#spacetime", where: "Spacetime", q: "Is there one 'now' for everyone?", see: "Two lamps flash together — or do they?",
        say: "Set the speed to 0.6 c, then press 'Draw it their way'.", look: "the table: the order of A and B for each observer",
        takeaway: "'At the same time' depends on who's asking — but cause and effect never swap places.", tags: ["ESTABLISHED"],
        limit: "Special relativity; one space dimension.", handoff: "If 'now' depends on who's asking, what is 'now' at all?",
        setup: { mode: "now", v: 0.6 } },
      { href: "#flatland/7", where: "Flatland", q: "So what is 'now'?", see: "A whole history stacked into one block.",
        say: "Move the slice through the block — a way of exploring the diagram, not something physical moving.", look: "the whole history in one shape",
        takeaway: "In the block picture every moment is equally there, and nothing marks one as 'now'. That's why 'now' is a puzzle.", tags: ["ESTABLISHED", "CONTESTED"],
        limit: "The block is one interpretation (hole H4); a growing block is a live alternative.", handoff: "A block has no 'now' and no direction. So why does time feel like it runs one way?" },
      { href: "#entropy", where: "Entropy box", q: "Why does time only run one way?", see: "A gas spreads out. Can you make it gather back?",
        say: "Remove the wall, wait, reverse every velocity. Then try it with the nudge.", look: "the entropy curve and the left-half count",
        takeaway: "The arrow comes from the odds, not the laws — plus a universe that started ordered (why it did is an open hole).", tags: ["ESTABLISHED"],
        limit: "A 2-D gas of 240 soft discs; integer arithmetic makes the reversal exact.", handoff: "We've asked why time has a direction. A different puzzle is why it has only one dimension. What would two do?" },
      { href: "#films", where: "Two Films", q: "What would two times do?", see: "Two identical starting frames. Watch what happens next.",
        say: "Press play on two films that start from exactly the same frame — same shape, same rates of change.", look: "where the films diverge",
        takeaway: "For the equation and complete starting data shown, the future isn't fixed; with one time it would be. A serious constraint on two-time theories, not a proof they're impossible.", tags: ["ESTABLISHED", "CONTESTED"],
        limit: "Exact solutions of one wave equation with two times: a toy, not a universe.", handoff: "That's a strong constraint on two times. Is it why there's only one — or just how things happen to be?" },
      { href: "#atlas/H5", where: "The Atlas", q: "Is one time dimension a law of nature?", see: "Everyone who has tried to answer it — and how far they got.",
        say: "Strong constraints, no settled answer. Click three ideas on H5 and read their test-bench scores.", look: "which ideas clear which hurdles",
        takeaway: "Strong constraints, no settled answer.", tags: ["CONTESTED"], limit: "The scores are first-pass judgements, made to be argued with.", handoff: "" }
    ] },
    zoom: { name: "From the ISS to the edge of the universe", blurb: "If you'd rather start with astronauts and spacecraft — then zoom out to the edge of the universe, in space and in time.", stops: [
      { href: "#missions", where: "Mission clocks", q: "Does space travel make you younger?", see: "Clocks on the ISS, on GPS satellites, on the Moon.",
        say: "Pick ISS, then GPS, then Moon base. Which effect wins at each?", look: "the net bar and the six-month total",
        takeaway: "Six months on the ISS: about 4.5 thousandths of a second younger. Real, measured, far too small to feel.", tags: ["ESTABLISHED"],
        limit: "Weak-field formulas; circular orbits.", handoff: "Clocks on the Moon and Mars tick at different rates. But could you even hold a conversation with Mars?" },
      { href: "#mars", where: "Talking to Mars", q: "Can we talk to Mars live?", see: "A question and answer that take the best part of an hour.",
        say: "Press Farthest, then send a message. Watch it cross the spacetime diagram.", look: "the message crossing the diagram",
        takeaway: "We see Mars as it was minutes ago. To say what's happening there now, we must choose how to synchronise distant clocks — and observers moving differently can choose differently.", tags: ["ESTABLISHED"],
        limit: "Circular, coplanar orbits. Signal delay alone doesn't show observers disagreeing; Spacetime does.", handoff: "Light is the speed limit for messages. Is it also a limit on how far people can go?",
        go: [["#spacetime", "Spacetime · Whose 'now'?"]], setup: { far: true }, predict: null },
      { href: "#voyage", where: "The 1 g voyage", q: "How far could you go in a lifetime?", see: "The centre of the galaxy — by your own clock.",
        say: "Fly to Proxima, then the centre of the galaxy. Watch the crew's clock against Earth's.", look: "crew years against Earth years",
        takeaway: "The galaxy's centre in about 20 years of crew time, while about 26,000 years pass on Earth. Nothing passes light speed; the fuel is another matter.", tags: ["ESTABLISHED"],
        limit: "Constant proper acceleration; the fuel mass is shown, not solved.", handoff: "Our own clocks could carry us across the galaxy. But the galaxies themselves are moving apart. Are we at the centre?",
        setup: { dest: "gc" } },
      { href: "#expand", where: "Expanding universe", q: "Is everything flying away from us?", see: "Stand on any galaxy and look around.",
        say: "Click three different galaxies to stand on.", look: "the arrows from each viewpoint",
        takeaway: "On large scales, distant galaxies show the same expansion pattern from any galaxy's viewpoint; no galaxy is at the centre. Nearby, gravity holds groups together.", tags: ["ESTABLISHED"],
        limit: "A flat universe with Planck 2018 values; the exact rate is contested (the Hubble tension).", handoff: "If space keeps stretching, how far can we ever see, and how far could we ever reach?",
        predict: null },
      { href: "#horizons", where: "Cosmic horizons", q: "How far can we ever see?", see: "46 billion light-years — and a horizon no message can cross.",
        say: "Drag the galaxy outward past both edges.", look: "the teardrop past light cone and the event horizon",
        takeaway: "Two edges: how far we can see, and how far we can ever reach — and galaxies slip past the second all the time.", tags: ["ESTABLISHED"],
        limit: "Standard cosmology (ΛCDM), Planck 2018 values.", handoff: "That's the edge in space. Where are we in the universe's story — and how far into the future can we trace it?" },
      { href: "#timeline", where: "Cosmic timeline", q: "How far into the future can we trace the universe's story?", see: "From the first second to the last black hole.",
        say: "Step through the events with ◀ ▶, then switch to Ordinary time.", look: "'you are here' on the axis, and the one-year calendar",
        takeaway: "Today sits about 40% across this powers-of-ten chart — a place on a chart with chosen endpoints, not a share of the universe's life. On an ordinary clock the story has barely begun.", tags: ["ESTABLISHED"],
        limit: "Published times, not computed; the far future assumes today's physics holds.", handoff: "",
        go: [["#janus", "Where does time's arrow come from? · The Janus point"], ["#boot", "Why three space dimensions and one time? · Boot a Universe"]], setup: { mode: "log", sel: 12 } }
    ] },
    time: { name: "Is time travel possible?", blurb: "If you'd like the question everyone asks first: into the future, into the past — what the physics actually allows.", stops: [
      { href: "#clocks", where: "Clock Lab", q: "Can you travel into the future?", see: "Yes — every moving clock does it. By how much?",
        say: "The moving clock is at 0.99 of light speed. Read how many of your years pass for one of its.", look: "the years readout under the clocks",
        takeaway: "In your frame, a moving clock records less time. A traveller who comes back has aged less — and steps into your future.", tags: ["ESTABLISHED"],
        limit: "One-way view; coming back is stop 3.", handoff: "Moving clocks run slow. How far into Earth's future could a person really go?",
        setup: { mode: "light", v: 0.99 },
        predict: { q: "A traveller moves at 0.99 of light speed. Their clock shows 1 year. In your frame, how much time passes for you?",
          options: ["About 1 year", "About 7 years", "About 100 years"], answer: 1,
          explain: "About 7. At 0.99 c the factor γ is 7.1: in your frame, their clock records one year while yours records about seven. When a traveller comes back, they've aged less — they've stepped into your future. (Why the traveller and not you? Stop 3.)" } },
      { href: "#voyage", where: "The 1 g voyage", q: "How far into the future could you go?", see: "The galaxy's centre and back — how much older is Earth?",
        say: "Fly to the centre of the galaxy, then read the 'there and back' line.", look: "Earth years against crew years, there and back",
        takeaway: "For a symmetric round trip — 1 g to halfway, 1 g braking, then the same back — about 40 years of crew time; about 52,000 years pass on Earth. A one-way ticket to the future.", tags: ["ESTABLISHED"],
        limit: "Constant 1 g; the fuel is the real barrier (shown, not solved).", handoff: "That's a one-way trip forward. Why can't you turn round and come back to the same time?",
        setup: { dest: "gc" }, predict: null },
      { href: "#spacetime", where: "Spacetime", q: "Why can't you just come back?", see: "Light cones, and a twin who turns round.",
        say: "Twin paradox: 0.8 c to a star 4 light-years away and back. Read both clocks at the reunion.", look: "the two clocks at the reunion",
        takeaway: "The traveller really is younger — 6 years to Earth's 10 — and coming back doesn't undo it. Only the traveller changes frame.", tags: ["ESTABLISHED"],
        limit: "An instant turnaround; special relativity.", handoff: "Forwards is easy. Backwards needs something stranger than speed. Could a black hole bend time enough?",
        setup: { mode: "twins", twinV: 0.8, twinD: 4 },
        predict: { q: "One twin flies to a star 4 light-years away at 0.8 of light speed, and back. The Earth twin ages 10 years. When they meet again, the traveller has aged…",
          options: ["10 years — motion is relative", "About 6 years", "0 years"], answer: 1,
          explain: "About 6. Only the traveller turns round, changing frame. Add it up from either side and the answers agree: 10 years at home, 6 on the ship. The difference is real and permanent — measured with atomic clocks and fast muons." } },
      { href: "#river", where: "The River", q: "Could a black hole be a shortcut?", see: "Space flowing in faster than light can swim out.",
        say: "Fire light outward from just inside the horizon.", look: "the flash being swept inward",
        takeaway: "A black hole is a trap, not a shortcut: once inside, every path leads to the centre.", tags: ["ESTABLISHED"],
        limit: "A non-rotating black hole; spinning ones are stranger (not shown).", handoff: "A black hole is a trap. But an idealised, eternal black-hole solution contains a bridge to somewhere else — could you cross that?",
        predict: { q: "You fall through a large black hole's horizon. Can any rocket, however powerful, get you back out?",
          options: ["Yes, with enough power", "No — inside, the centre is in your future", "Yes, but only a little way"], answer: 1,
          explain: "No. Inside the horizon, space flows inward faster than light, and every direction you can move in leads to the centre — as surely as every path leads to tomorrow. The horizon is a point of no return, not a wall." } },
      { href: "#wormhole", where: "Wormholes", q: "Can you cross a wormhole?", see: "Einstein and Rosen's bridge between two universes.",
        say: "Fire light inward, then watch the bridge open and close.", look: "every ray ending at the singularity; the throat shrinking",
        takeaway: "The bridge is real mathematics but can't be crossed; one you could cross would need exotic matter with negative energy.", tags: ["ESTABLISHED", "SPECULATIVE"],
        limit: "The eternal black hole; black holes formed from stars have no bridge.", handoff: "Bridges pinch shut. What about a whole universe that loops time back on itself?",
        predict: null },
      { href: "#loops", where: "Time loops", q: "Could you loop back into your own past?", see: "A spinning universe where light cones tip over.",
        say: "Slide past the critical radius and walk the circle.", look: "the light cone tipping over the circle",
        takeaway: "Einstein's equations allow time loops; our universe doesn't rotate measurably, and nobody knows whether nature forbids them.", tags: ["ESTABLISHED", "CONTESTED"],
        limit: "Gödel's exact solution; it doesn't expand, unlike ours.", handoff: "So what's the verdict?" },
      { href: "#concepts/timetravel", where: "Concept", q: "So — is time travel possible?", see: "Forward, backward, paradoxes — the verdict.",
        say: "The verdict, with the paradoxes and Hawking's party for time travellers.", look: "the three recipes and what each needs",
        takeaway: "Forwards: yes, and measured every day. Backwards: allowed by some solutions, never seen, and every recipe needs something our universe lacks.", tags: ["ESTABLISHED", "CONTESTED"],
        limit: "", handoff: "" }
    ] }
  };
})();
